"""
Django settings for lera project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])

BASE_URL = config('BASE_URL')
BASE_URL_PREFIX = f"http://{BASE_URL}" if BASE_URL == '127.0.0.1:8000' else BASE_URL

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',

    'analytical',
    'bootstrap_modal_forms',
    # 'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_celery_results',
    'django_cleanup.apps.CleanupConfig',
    'django_filters',
    'django_htmx',
    'django_user_agents',
    'django_tables2',
    'django_tables2_column_shifter',
    'django_select2',
    'multi_form_view',
    'pgcrypto',
    'robots',
    'storages',
    'thumbnails',

    'accounts',
    'cms',
    'dashboard',
    'landing'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'lera.middleware.DefaultLanguageMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lera.middleware.HtmxMessageMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'lera.middleware.AjaxMiddleware'
]

ROOT_URLCONF = 'lera.urls'
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/account/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                (
                    'django.template.loaders.cached.Loader',
                    [
                        'django.template.loaders.app_directories.Loader',
                        'django.template.loaders.filesystem.Loader'
                    ]
                )
            ]
        },
    },
]

ASGI_APPLICATION = 'lera.asgi.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('CELERY_BROKER_URL')]
        }
    }
}
CHANNELS_WS_PROTOCOL_MAX_MESSAGE_SIZE = 5242880 * 2  # 5MB (default)
CHANNELS_HTTP_MAX_POST_SIZE = 5242880 * 2  # 5MB (default)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'default_cache',
        "TIMEOUT": 60,
        "OPTIONS": {"MAX_ENTRIES": 1000},
    },
    'celery': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'celery_cache',
    },
    'select2': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'select2_cache',
        'TIMEOUT': 60 * 60 * 12,
    }
}

SELECT2_CACHE_BACKEND = "select2"

CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND')

CELERY_BROKER_POOL_LIMIT = 1
CELERY_BROKER_CONNECTION_TIMEOUT = 10
CELERY_CONCURRENCY = 4
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_TIMEZONE = "Asia/Jakarta"
CELERY_ENABLE_UTC = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

if not BASE_URL == '127.0.0.1:8000':
    CACHES['celery']['BACKEND'] = "django.core.cache.backends.memcached.PyMemcacheCache"
    CACHES['celery']['LOCATION'] = "unix:/tmp/memcached.sock"

if not BASE_URL == '127.0.0.1:8000':
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "root": {"level": "INFO", "handlers": ["file"]},
        "handlers": {
            "file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": "/home/ubuntu/gunicorn/warning.log",
                "formatter": "app",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["file"],
                "level": "INFO",
                "propagate": True
            },
        },
        "formatters": {
            "app": {
                "format": (
                    u"%(asctime)s [%(levelname)-8s] "
                    "(%(module)s.%(funcName)s) %(message)s"
                ),
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
        },
    }


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'assets/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets'
]

STATIC_ROOT = BASE_DIR / 'cdn/static_root'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'cdn/media_root'

PROTECTED_ROOT = BASE_DIR / 'cdn/protected'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FILE_STORAGE = config('DEFAULT_FILE_STORAGE')

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

THUMBNAILS = {
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
    'STORAGE': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        # You can also use Amazon S3 or any other Django storage backends
    },
    'SIZES': {
        'avatar': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 150, 'height': 150},
            ],
        },
        'small': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 46, 'height': 46}
            ],
            'POST_PROCESSORS': [
                {
                    'PATH': 'thumbnails.post_processors.optimize',
                    'png_command': 'optipng -force -o7 "%(filename)s"',
                    'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
                },
            ],
        },
        'large': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 600, 'height': 600},
            ],
        },
        'medium': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 150, 'height': 150},
                {'PATH': 'thumbnails.processors.crop', 'width': 100, 'height': 100}
            ],
        },
        'watermarked': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                {'PATH': 'thumbnails.processors.add_watermark', 'watermark_path': 'watermark.png'}
            ],
        }
    }
}

SELECT2_CSS = []

DEFAULT_ACTIVATION_DAYS = 2

DATA_UPLOAD_MAX_MEMORY_SIZE = 3145728

DJANGO_TABLES2_TEMPLATE = 'bootstrap5/table-bootstrap5-responsive.html'

PGCRYPTO_DEFAULT_CIPHER = "aes"
PGCRYPTO_DEFAULT_KEY = SECRET_KEY

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

if not BASE_URL == '127.0.0.1:8000':
    CSRF_TRUSTED_ORIGINS = [
        "https://*.lera.or.id/",
        "https://lera.or.id/",
        "https://www.lera.or.id/"
    ]

CLICKY_SITE_ID = config('CLICKY_SITE_ID')
ANALYTICAL_INTERNAL_IPS = ['127.0.0.1', '182.253.55.74']

ROBOTS_SITEMAP_URLS = ['https://lera.or.id/sitemap.xml']
ROBOTS_SITEMAP_VIEW_NAME = 'cached_sitemap'
ROBOTS_USE_HOST = False
ROBOTS_USE_SCHEME_IN_HOST = False

GOOGLE_ANALYTICS_GTAG_PROPERTY_ID = config('GOOGLE_ANALYTICS_GTAG_PROPERTY_ID')